POST http://localhost:3000/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsImV4cCI6MTc2MzIyNTczMCwidXNlcklkIjowfQ.5EjdsdfvfKQuF9i4tZW_DH8fdi3MkjgMJt_vxpIZ-ac

{
    "name": "Test event 2",
    "description": "Another test event",
    "location": "A test location",
    "dateTime": "2025-11-08T11:28:00.000Z"
}
